import Foundation
import SwiftData

// MARK: - Row types per CSV section

struct AccountCSVRow {
    var name: String
    var typeRaw: String
    var balance: Double
    var currency: String
    var provider: String
    var growthRate: Double
    var isVisible: Bool
    var kaufpreis: Double = 0
    var kaufdatum: Date? = nil
    var hypothekBetrag: Double = 0
    var hypothekZinssatz: Double = 0
    var linked3aAccountID: String = ""
}

struct BudgetEntryCSVRow {
    var date: Date
    var category: String
    var mainCategory: String
    var amount: Double
    var currency: String
    var recurrence: String
    var isActive: Bool
    var account: String
    var transferTo: String  // linked transfer-target account name
    var description: String
}

struct GoalCSVRow {
    var name: String
    var categoryRaw: String
    var targetAmount: Double
    var currency: String
    var priority: Int
    var isActive: Bool
}

struct UserCategoryCSVRow {
    var name: String
    var symbolName: String
    var colorRaw: String
    var isIncome: Bool
    var isSavings: Bool
    var isInvestment: Bool
    var groupRaw: String
}

struct TransactionCSVRow {
    var date: Date
    var valueDate: Date
    var description: String
    var merchantName: String
    var rawAmount: Double   // signed: negative=expense, positive=income
    var category: String
    var currency: String
    var account: String
    var userNote: String
    var bankFormatRaw: String
}

struct TransactionCategoryCSVRow {
    var name: String
    var symbolName: String
    var colorHex: String
    var groupRaw: String
}

struct CategoryRuleCSVRow {
    var keyword: String
    var categoryRaw: String
    var isAutoGenerated: Bool
    var amountMin: Double?
    var amountMax: Double?
    var accountIDs: [UUID]
}

struct CSVImportData {
    var accounts: [AccountCSVRow] = []
    var budgetEntries: [BudgetEntryCSVRow] = []
    var goals: [GoalCSVRow] = []
    var userCategories: [UserCategoryCSVRow] = []
    var transactions: [TransactionCSVRow] = []
    var transactionCategories: [TransactionCategoryCSVRow] = []
    var categoryRules: [CategoryRuleCSVRow] = []
}

// MARK: - Import result

struct CSVImportResult {
    var accounts: Int    = 0
    var entries: Int     = 0
    var goals: Int       = 0
    var categories: Int  = 0
    var transactions: Int = 0
    var transactionCategories: Int = 0
    var categoryRules: Int = 0
}

// MARK: - Errors

enum CSVParseError: LocalizedError {
    case emptyData
    case invalidHeader
    case invalidDate(row: Int)
    case invalidAmount(row: Int)

    var errorDescription: String? {
        switch self {
        case .emptyData:
            return NSLocalizedString("csv_error_empty", comment: "")
        case .invalidHeader:
            return NSLocalizedString("csv_error_header", comment: "")
        case .invalidDate(let row):
            return String(format: NSLocalizedString("csv_error_date_format", comment: ""), row)
        case .invalidAmount(let row):
            return String(format: NSLocalizedString("csv_error_amount", comment: ""), row)
        }
    }
}

enum CSVExportManager {

    // MARK: - Section markers

    private static let sectionAccounts     = "[Accounts]"
    private static let sectionBudget       = "[BudgetEntries]"
    private static let sectionGoals        = "[Goals]"
    private static let sectionUserCats     = "[UserCategories]"
    private static let sectionTransactions  = "[Transactions]"
    private static let sectionTxCats        = "[TransactionCategories]"
    private static let sectionCategoryRules = "[CategoryRules]"

    private static let accountHeader       = "Name,Type,Balance,Currency,Provider,GrowthRate,IsVisible,Kaufpreis,Kaufdatum,HypothekBetrag,HypothekZinssatz,Linked3aAccountID"
    private static let budgetHeader        = "Date,Category,Main Category,Amount,Currency,Recurrence,IsActive,Account,TransferTo,Description"
    private static let goalHeader          = "Name,Category,TargetAmount,Currency,Priority,IsActive"
    private static let userCatHeader       = "Name,Symbol,Color,IsIncome,IsSavings,IsInvestment,Group"
    private static let transactionHeader    = "Date,ValueDate,Description,MerchantName,Amount,Category,Currency,Account,Note,BankFormat"
    private static let txCatHeader          = "Name,Symbol,ColorHex,Group"
    private static let categoryRuleHeader   = "Keyword,CategoryRaw,IsAutoGenerated,AmountMin,AmountMax,AccountIDs"

    private static let dateFormatter: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "yyyy-MM-dd"
        f.locale = Locale(identifier: "en_US_POSIX")
        f.timeZone = TimeZone(identifier: "UTC")
        return f
    }()

    // MARK: - Export

    static func export(
        accounts: [Account],
        entries: [BudgetEntry],
        goals: [FinancialGoal],
        userCategories: [UserBudgetCategory] = [],
        transactions: [ImportedTransaction] = [],
        transactionCategories: [UserTransactionCategory] = [],
        categoryRules: [CategoryRule] = [],
        defaultCurrency: String
    ) -> String {
        var lines: [String] = []

        // Accounts section
        if !accounts.isEmpty {
            lines.append(sectionAccounts)
            lines.append(accountHeader)
            for acc in accounts {
                let row = [
                    escaped(acc.name),
                    escaped(acc.typeRaw),
                    String(format: "%.2f", acc.balance),
                    escaped(acc.currency),
                    escaped(acc.provider),
                    String(format: "%.4f", acc.annualGrowthRate),
                    acc.isVisible ? "true" : "false",
                    String(format: "%.2f", acc.kaufpreis),
                    acc.kaufdatum.map { dateFormatter.string(from: $0) } ?? "",
                    String(format: "%.2f", acc.hypothekBetrag),
                    String(format: "%.4f", acc.hypothekZinssatz),
                    escaped(acc.linked3aAccountID)
                ]
                lines.append(row.joined(separator: ","))
            }
            lines.append("")
        }

        // Budget entries section
        if !entries.isEmpty {
            lines.append(sectionBudget)
            lines.append(budgetHeader)
            for entry in entries {
                let row = [
                    dateFormatter.string(from: entry.dueDate),
                    escaped(entry.displayName),
                    escaped(mainCategoryLabel(for: entry)),
                    String(format: "%.2f", entry.amount),
                    escaped(entry.currencyOverride ?? defaultCurrency),
                    escaped(entry.recurrenceRaw),
                    entry.isActive ? "true" : "false",
                    escaped(entry.account?.name ?? ""),
                    escaped(entry.transferToAccount?.name ?? ""),
                    escaped(entry.notes)
                ]
                lines.append(row.joined(separator: ","))
            }
            lines.append("")
        }

        // Goals section
        if !goals.isEmpty {
            lines.append(sectionGoals)
            lines.append(goalHeader)
            for goal in goals {
                let row = [
                    escaped(goal.name),
                    escaped(goal.categoryRaw),
                    String(format: "%.2f", goal.targetAmount),
                    escaped(goal.currency),
                    String(goal.priority),
                    goal.isActive ? "true" : "false"
                ]
                lines.append(row.joined(separator: ","))
            }
            lines.append("")
        }

        // User categories section
        if !userCategories.isEmpty {
            lines.append(sectionUserCats)
            lines.append(userCatHeader)
            for cat in userCategories {
                let row = [
                    escaped(cat.name),
                    escaped(cat.symbolName),
                    escaped(cat.colorNameRaw),
                    cat.isIncome ? "true" : "false",
                    cat.isSavings ? "true" : "false",
                    cat.isInvestment ? "true" : "false",
                    escaped(cat.groupRaw)
                ]
                lines.append(row.joined(separator: ","))
            }
        }

        // Transactions section
        if !transactions.isEmpty {
            lines.append("")
            lines.append(sectionTransactions)
            lines.append(transactionHeader)
            let sorted = transactions.sorted { $0.date > $1.date }
            for tx in sorted {
                let row = [
                    dateFormatter.string(from: tx.date),
                    dateFormatter.string(from: tx.valueDate),
                    escaped(tx.transactionDescription),
                    escaped(tx.merchantName),
                    String(format: "%.2f", tx.rawAmount),
                    escaped(tx.categoryRaw),
                    escaped(tx.currencyCode),
                    escaped(tx.account?.name ?? ""),
                    escaped(tx.userNote),
                    escaped(tx.bankFormatRaw)
                ]
                lines.append(row.joined(separator: ","))
            }
        }

        // Transaction categories section
        if !transactionCategories.isEmpty {
            lines.append("")
            lines.append(sectionTxCats)
            lines.append(txCatHeader)
            for cat in transactionCategories {
                let row = [
                    escaped(cat.name),
                    escaped(cat.systemImage),
                    escaped(cat.colorHex),
                    escaped(cat.groupRaw)
                ]
                lines.append(row.joined(separator: ","))
            }
        }

        // Category rules section (from Analyse / bank import)
        if !categoryRules.isEmpty {
            lines.append("")
            lines.append(sectionCategoryRules)
            lines.append(categoryRuleHeader)
            for rule in categoryRules {
                let minStr = rule.amountMin.map { String(format: "%.2f", $0) } ?? ""
                let maxStr = rule.amountMax.map { String(format: "%.2f", $0) } ?? ""
                let idsStr = rule.accountIDs.map { $0.map(\.uuidString).joined(separator: "|") } ?? ""
                let row = [
                    escaped(rule.keyword),
                    escaped(rule.categoryRaw),
                    rule.isAutoGenerated ? "true" : "false",
                    minStr,
                    maxStr,
                    escaped(idsStr)
                ]
                lines.append(row.joined(separator: ","))
            }
        }

        return lines.joined(separator: "\n")
    }

    static func generateTempFile(csvString: String) throws -> URL {
        let name = "financehelper-\(dateFormatter.string(from: Date())).csv"
        let url  = FileManager.default.temporaryDirectory.appendingPathComponent(name)
        try csvString.write(to: url, atomically: true, encoding: .utf8)
        // Exclude from iCloud/iTunes backup — this is a transient export file with sensitive data.
        try? (url as NSURL).setResourceValue(true, forKey: .isExcludedFromBackupKey)
        return url
    }

    // MARK: - Parse

    static func parse(csvString: String) -> Result<CSVImportData, CSVParseError> {
        let lines = csvString
            .components(separatedBy: "\n")
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
        guard !lines.isEmpty else { return .failure(.emptyData) }

        // Detect old 6-column or 9-column single-section format (starts with "Date,")
        if lines[0].hasPrefix("Date,") {
            return parseLegacyBudgetOnly(lines: lines)
        }

        // New multi-section format (starts with "[")
        guard lines[0].hasPrefix("[") else { return .failure(.invalidHeader) }
        return parseMultiSection(lines: lines)
    }

    // MARK: - Import

    static func importData(
        _ data: CSVImportData,
        into context: ModelContext,
        profileID: String,
        existingAccounts: [Account],
        existingEntries: [BudgetEntry],
        existingCategories: [UserBudgetCategory],
        existingGoals: [FinancialGoal],
        existingTransactions: [ImportedTransaction] = [],
        existingTxCategories: [UserTransactionCategory] = []
    ) throws -> CSVImportResult {
        var result = CSVImportResult()

        // --- Accounts ---
        // Build name→Account map from existing accounts; newly imported ones are added too
        // so budget entries processed below can link to accounts imported in the same pass.
        var accountMap: [String: Account] = Dictionary(
            existingAccounts.map { ($0.name.lowercased(), $0) },
            uniquingKeysWith: { first, _ in first }
        )
        let existingAccountKeys = Set(existingAccounts.map { "\($0.name.lowercased())|\($0.typeRaw)" })
        for row in data.accounts {
            let key = "\(row.name.lowercased())|\(row.typeRaw)"
            guard !existingAccountKeys.contains(key) else { continue }
            let account = Account(
                name: row.name,
                type: AccountType(rawValue: row.typeRaw) ?? .girokonto,
                balance: row.balance,
                currency: row.currency
            )
            account.profileID         = profileID
            account.provider          = row.provider
            account.annualGrowthRate  = row.growthRate
            account.isVisible         = row.isVisible
            account.kaufpreis         = row.kaufpreis
            account.kaufdatum         = row.kaufdatum
            account.hypothekBetrag    = row.hypothekBetrag
            account.hypothekZinssatz  = row.hypothekZinssatz
            account.linked3aAccountID = row.linked3aAccountID
            context.insert(account)
            accountMap[row.name.lowercased()] = account
            result.accounts += 1
        }

        // --- Budget entries ---
        var categoryMap = Dictionary(
            uniqueKeysWithValues: existingCategories.map { ($0.name.lowercased(), $0) }
        )
        for row in data.budgetEntries {
            let isDuplicate = existingEntries.contains {
                Calendar.current.isDate($0.dueDate, inSameDayAs: row.date)
                    && $0.amount == row.amount
                    && $0.notes  == row.description
            }
            guard !isDuplicate else { continue }

            var budgetCategory: BudgetCategory = .lebensmittel
            var userCategory: UserBudgetCategory?

            if let matched = BudgetCategory.allCases.first(where: {
                $0.rawValue == row.category || $0.localizedName == row.category
            }) {
                budgetCategory = matched
            } else {
                let key = row.category.lowercased()
                if let existing = categoryMap[key] {
                    userCategory = existing
                } else {
                    let isIncome = row.mainCategory.lowercased() == "income"
                    let newCat   = UserBudgetCategory(name: row.category,
                                                      symbolName: "tag.fill",
                                                      color: .blue,
                                                      isIncome: isIncome)
                    context.insert(newCat)
                    categoryMap[key] = newCat
                    userCategory     = newCat
                }
            }

            let recurrence         = BudgetRecurrence(rawValue: row.recurrence) ?? .monthly
            let entry              = BudgetEntry(category: budgetCategory,
                                                 amount: row.amount,
                                                 recurrence: recurrence,
                                                 dueDate: row.date)
            entry.notes            = row.description
            entry.isActive         = row.isActive
            entry.profileID        = profileID
            entry.currencyOverride = row.currency.isEmpty ? nil : row.currency
            entry.userCategory     = userCategory
            if !row.account.isEmpty { entry.account = accountMap[row.account.lowercased()] }
            if !row.transferTo.isEmpty { entry.transferToAccount = accountMap[row.transferTo.lowercased()] }
            context.insert(entry)
            result.entries += 1
        }

        // --- Goals ---
        let existingGoalNames = Set(existingGoals.map { $0.name.lowercased() })
        for row in data.goals {
            guard !existingGoalNames.contains(row.name.lowercased()) else { continue }
            let goal = FinancialGoal(
                profileID:    profileID,
                name:         row.name,
                category:     GoalCategory(rawValue: row.categoryRaw) ?? .custom,
                targetAmount: row.targetAmount,
                currency:     row.currency
            )
            goal.priority = row.priority
            goal.isActive = row.isActive
            context.insert(goal)
            result.goals += 1
        }

        // --- User categories ---
        let existingCatNames = Set(existingCategories.map { $0.name.lowercased() })
        for row in data.userCategories {
            guard !existingCatNames.contains(row.name.lowercased()) else { continue }
            let cat = UserBudgetCategory(
                name:         row.name,
                symbolName:   row.symbolName,
                color:        CategoryColor(rawValue: row.colorRaw) ?? .blue,
                isIncome:     row.isIncome,
                isSavings:    row.isSavings,
                isInvestment: row.isInvestment,
                group:        BudgetCategoryGroup(rawValue: row.groupRaw) ?? .lifestyle,
                profileID:    profileID
            )
            context.insert(cat)
            result.categories += 1
        }

        // --- Transactions ---
        for row in data.transactions {
            let isDuplicate = existingTransactions.contains {
                Calendar.current.isDate($0.date, inSameDayAs: row.date)
                    && $0.transactionDescription == row.description
                    && $0.rawAmount == row.rawAmount
            }
            guard !isDuplicate else { continue }
            let tx = ImportedTransaction(from: BankTransaction(
                date: row.date,
                description: row.description,
                rawAmount: row.rawAmount,
                valueDate: row.valueDate,
                category: TransactionCategory(rawValue: row.category) ?? .sonstiges,
                merchantName: row.merchantName,
                currencyCode: row.currency
            ), bank: BankFormat(rawValue: row.bankFormatRaw) ?? .zugerKantonalbank, profileID: profileID)
            tx.userNote = row.userNote
            if !row.account.isEmpty { tx.account = accountMap[row.account.lowercased()] }
            context.insert(tx)
            result.transactions += 1
        }

        // --- Transaction categories ---
        let existingTxCatNames = Set(existingTxCategories.map { $0.name.lowercased() })
        for row in data.transactionCategories {
            guard !existingTxCatNames.contains(row.name.lowercased()) else { continue }
            let cat = UserTransactionCategory(
                name:        row.name,
                systemImage: row.symbolName,
                colorHex:    row.colorHex,
                group:       CategoryGroup(rawValue: row.groupRaw) ?? .lifestyle,
                profileID:   profileID
            )
            context.insert(cat)
            result.transactionCategories += 1
        }

        // --- Category rules (UserDefaults, not SwiftData) ---
        if !data.categoryRules.isEmpty {
            var existing = CustomRulesStore.load(profileID: profileID)
            let existingKeywords = Set(existing.map { $0.keyword.uppercased() })
            for row in data.categoryRules {
                let kw = row.keyword.uppercased()
                guard !kw.isEmpty, !existingKeywords.contains(kw) else { continue }
                existing.append(CategoryRule(
                    keyword:         row.keyword,
                    categoryRaw:     row.categoryRaw,
                    isAutoGenerated: row.isAutoGenerated,
                    amountMin:       row.amountMin,
                    amountMax:       row.amountMax,
                    accountIDs:      row.accountIDs.isEmpty ? nil : row.accountIDs
                ))
                result.categoryRules += 1
            }
            if result.categoryRules > 0 {
                CustomRulesStore.save(existing, profileID: profileID)
            }
        }

        try context.save()
        return result
    }

    // MARK: - Private parsers

    private static func parseMultiSection(lines: [String]) -> Result<CSVImportData, CSVParseError> {
        enum Section { case none, accounts, budget, goals, userCats, transactions, txCats, categoryRules }

        var data         = CSVImportData()
        var section      = Section.none
        var skipHeader   = false
        var rowIndex     = 0

        for line in lines {
            rowIndex += 1
            if line == sectionAccounts       { section = .accounts;       skipHeader = true; continue }
            if line == sectionBudget         { section = .budget;         skipHeader = true; continue }
            if line == sectionGoals          { section = .goals;          skipHeader = true; continue }
            if line == sectionUserCats       { section = .userCats;       skipHeader = true; continue }
            if line == sectionTransactions   { section = .transactions;   skipHeader = true; continue }
            if line == sectionTxCats         { section = .txCats;         skipHeader = true; continue }
            if line == sectionCategoryRules  { section = .categoryRules;  skipHeader = true; continue }
            if skipHeader                    { skipHeader = false;  continue }

            let f = parseCSVLine(line)
            switch section {
            case .accounts:
                guard f.count >= 7 else { continue }
                guard let balance = Double(f[2]) else { continue }
                data.accounts.append(AccountCSVRow(
                    name:              f[0],
                    typeRaw:           f[1],
                    balance:           balance,
                    currency:          f[3],
                    provider:          f[4],
                    growthRate:        Double(f[5]) ?? 0,
                    isVisible:         f[6].lowercased() == "true",
                    kaufpreis:         f.count > 7  ? (Double(f[7])  ?? 0) : 0,
                    kaufdatum:         f.count > 8  && !f[8].isEmpty  ? dateFormatter.date(from: f[8])  : nil,
                    hypothekBetrag:    f.count > 9  ? (Double(f[9])  ?? 0) : 0,
                    hypothekZinssatz:  f.count > 10 ? (Double(f[10]) ?? 0) : 0,
                    linked3aAccountID: f.count > 11 ? f[11] : ""
                ))
            case .budget:
                guard f.count >= 9 else { continue }
                guard let date = dateFormatter.date(from: f[0]) else { continue }
                guard let amount = Double(f[3]) else { continue }
                let hasTransferCol = f.count >= 10
                data.budgetEntries.append(BudgetEntryCSVRow(
                    date:         date,
                    category:     f[1],
                    mainCategory: f[2],
                    amount:       amount,
                    currency:     f[4],
                    recurrence:   f[5],
                    isActive:     f[6].lowercased() == "true",
                    account:      f[7],
                    transferTo:   hasTransferCol ? f[8] : "",
                    description:  hasTransferCol ? f[9] : f[8]
                ))
            case .goals:
                guard f.count >= 6 else { continue }
                guard let target = Double(f[2]) else { continue }
                data.goals.append(GoalCSVRow(
                    name:         f[0],
                    categoryRaw:  f[1],
                    targetAmount: target,
                    currency:     f[3],
                    priority:     Int(f[4]) ?? 0,
                    isActive:     f[5].lowercased() == "true"
                ))
            case .userCats:
                guard f.count >= 7 else { continue }
                data.userCategories.append(UserCategoryCSVRow(
                    name:         f[0],
                    symbolName:   f[1],
                    colorRaw:     f[2],
                    isIncome:     f[3].lowercased() == "true",
                    isSavings:    f[4].lowercased() == "true",
                    isInvestment: f[5].lowercased() == "true",
                    groupRaw:     f[6]
                ))
            case .transactions:
                guard f.count >= 9 else { continue }
                guard let date = dateFormatter.date(from: f[0]),
                      let valueDate = dateFormatter.date(from: f[1]) else { continue }
                guard let amount = Double(f[4]) else { continue }
                data.transactions.append(TransactionCSVRow(
                    date:         date,
                    valueDate:    valueDate,
                    description:  f[2],
                    merchantName: f[3],
                    rawAmount:    amount,
                    category:     f[5],
                    currency:     f[6],
                    account:      f[7],
                    userNote:     f.count >= 9 ? f[8] : "",
                    bankFormatRaw: f.count >= 10 ? f[9] : ""
                ))
            case .txCats:
                guard f.count >= 4 else { continue }
                data.transactionCategories.append(TransactionCategoryCSVRow(
                    name:       f[0],
                    symbolName: f[1],
                    colorHex:   f[2],
                    groupRaw:   f[3]
                ))
            case .categoryRules:
                guard f.count >= 3 else { continue }
                let accountIDs = f.count >= 6 && !f[5].isEmpty
                    ? f[5].split(separator: "|").compactMap { UUID(uuidString: String($0)) }
                    : [UUID]()
                data.categoryRules.append(CategoryRuleCSVRow(
                    keyword:         f[0],
                    categoryRaw:     f[1],
                    isAutoGenerated: f[2].lowercased() == "true",
                    amountMin:       f.count >= 4 && !f[3].isEmpty ? Double(f[3]) : nil,
                    amountMax:       f.count >= 5 && !f[4].isEmpty ? Double(f[4]) : nil,
                    accountIDs:      accountIDs
                ))
            case .none:
                break
            }
        }
        return .success(data)
    }

    private static func parseLegacyBudgetOnly(lines: [String]) -> Result<CSVImportData, CSVParseError> {
        var data = CSVImportData()
        for (offset, line) in lines.dropFirst().enumerated() {
            let rowIndex = offset + 2
            let f = parseCSVLine(line)
            guard f.count >= 6 else { continue }
            guard let date = dateFormatter.date(from: f[0]) else {
                return .failure(.invalidDate(row: rowIndex))
            }
            guard let amount = Double(f[3]) else {
                return .failure(.invalidAmount(row: rowIndex))
            }
            let isV2 = f.count >= 9
            let isV3 = f.count >= 10
            data.budgetEntries.append(BudgetEntryCSVRow(
                date:         date,
                category:     f[1],
                mainCategory: f[2],
                amount:       amount,
                currency:     f[4],
                recurrence:   isV2 ? f[5] : "monthly",
                isActive:     isV2 ? (f[6].lowercased() == "true") : true,
                account:      isV2 ? f[7] : "",
                transferTo:   isV3 ? f[8] : "",
                description:  isV3 ? f[9] : (isV2 ? f[8] : f[5])
            ))
        }
        return .success(data)
    }

    // MARK: - Helpers

    private static func mainCategoryLabel(for entry: BudgetEntry) -> String {
        let group: BudgetCategoryGroup
        if let uc = entry.userCategory {
            group = uc.isIncome     ? .einkommen
                  : uc.isInvestment ? .investieren
                  : uc.isSavings    ? .sparen
                  : .lifestyle
        } else {
            group = entry.category.group
        }
        switch group {
        case .einkommen:   return "Income"
        case .schulden:    return "Debt"
        case .fixkosten:   return "Fixed"
        case .lifestyle:   return "Lifestyle"
        case .sparen:      return "Savings"
        case .investieren: return "Investments"
        case .intern:      return "Internal"
        }
    }

    private static func escaped(_ string: String) -> String {
        // Prevent CSV injection: fields starting with formula-trigger characters are prefixed
        // with a tab so spreadsheet apps (Excel, Google Sheets) treat them as text, not formulas.
        var s = string
        if let first = s.first, first == "=" || first == "@" {
            s = "\t" + s
        }
        guard s.contains(",") || s.contains("\"") || s.contains("\n") || s.contains("\t") else {
            return s
        }
        return "\"" + s.replacingOccurrences(of: "\"", with: "\"\"") + "\""
    }

    private static func parseCSVLine(_ line: String) -> [String] {
        var fields: [String] = []
        var current  = ""
        var inQuotes = false
        var i        = line.startIndex

        while i < line.endIndex {
            let ch = line[i]
            if inQuotes {
                if ch == "\"" {
                    let next = line.index(after: i)
                    if next < line.endIndex && line[next] == "\"" {
                        current.append("\"")
                        i = line.index(after: next)
                        continue
                    }
                    inQuotes = false
                } else {
                    current.append(ch)
                }
            } else {
                if ch == "\"" {
                    inQuotes = true
                } else if ch == "," {
                    fields.append(current)
                    current = ""
                } else {
                    current.append(ch)
                }
            }
            i = line.index(after: i)
        }
        fields.append(current)
        return fields
    }
}
